### ISSUE TITLE
Consider other term then "Object"?

### ISSUE THREAD

**Issue by andrerom** [php-tag-store/php-tag-store#1]
This is naming nitpicking, but just to open the discussion before any implementation is added here.

As the interface is not really about storing the object themselves (_or `items` as it is called in psr-6)_, it should maybe either use the term `key` or just `id`.
### others
- [PSR-6](http://www.php-fig.org/psr/psr-6/#cacheiteminterface) uses `key`.
- [FOSHttpCache](https://github.com/FriendsOfSymfony/FOSHttpCache/tree/master/src/ProxyClient/Invalidation) afaik don't have a identifer atm, there is url, but it can have variations.
### interface

With key it might look something like:

``` php
interface TagStoreInterface
{
    public function tag($key, array $tags);
    public function untag($key, array $tags);
    public function getTags(array $keys);
    public function getKeys(array $tags);
    public function removeTags(array $tags);
    public function removeKeys(array $keys);
}
```

**Comment by magnusnordlander** [comment]
This is the exact right time for nitpicking :)

I'm not overly fond of the term key. PSR-6 uses key because it is a common term in the realm of caching. This on the other hand is for tagging anything. `id` works I suppose, but I am at least still somewhat partial to `objectId`, because that could make documentation a bit simpler.

**Comment by andrerom** [comment]
What about `itemId` ? :)  _(for me `object` is a bit alien in regards to cache, I can live with it, but it would then be different terminology then other libs around)_

On the other side, I do get your take I think; _this is not limited to caching._

**Comment by magnusnordlander** [comment]
I see `item` as being pretty equivalent to object when it comes to pros and cons, so I don't particularly mind it, but I do see a problem (shared by `object`) of having a method signature like the folliowing:

```
public function removeItems(array $itemIds);
```

Since you're _not_ actually passing an array of items (but rather item IDs) the method name is a little deceitful. Of course `removeItemIds` doesn't work either, because you're removing items from the tag store, not IDs. `removeItemsById` works, but is long.

I'm certainly open to changing the term, but is possible, let's find an even better one :)

**Comment by andrerom** [comment]
`removeByIds(array $itemIds)` could maybe work :)

**Comment by magnusnordlander** [comment]
That sounds pretty good, yeah.

**Comment by andrerom** [comment]
This would imply `removeByTags` as well, and it looks better since we are removing "`something`", aka either TagItem or TagObject or ... here, not just the tags or just the Ids separately.

**Comment by dantleech** [comment]
I used the term `cacheId` [here](https://github.com/sulu/sulu/pull/2210/files#diff-cd5dc3185849e36aa80b84d58514b2e5R4). Item ID sounds good to me.
objects is misleading.
